### ISSUE TITLE
部署后访问404

### ISSUE THREAD

**Issue by djksps1** [Mran/githubstartog#1]
大佬，部署后网页显示404，cloudflare和vercel部署都显示404，cloudflare和vercel都是这样，权限和GitHub Actions 构建都已完成，是哪一步我忽略了吗：
![image](https://github.com/user-attachments/assets/d15a749d-62d1-461d-9664-1c238e07ab32)
![image](https://github.com/user-attachments/assets/18c8f538-3a65-4620-b548-2e1193031de5)
![image](https://github.com/user-attachments/assets/5772e62a-7e7b-4874-af48-2da1dc42391c)

**Comment by Mran** [comment]
![image](https://github.com/user-attachments/assets/94bd6b27-1ddf-4788-a247-08f4a7377091)
可能是配置的构建路径错了，这是在pages中的构建配置。在vercel中是类似的。

**Comment by djksps1** [comment]
感谢，已成功部署

**Comment by cuixiping** [comment]
> ![image](https://github.com/user-attachments/assets/94bd6b27-1ddf-4788-a247-08f4a7377091) 可能是配置的构建路径错了，这是在pages中的构建配置。在vercel中是类似的。

这个应该写到`README.MD`文档中去
